version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/backend
    overwrite: yes
hooks:
  AfterInstall:
    - location: deployScripts/test.sh
      timeout: 60
      runas: ubuntu
